language: node_js
node_js:
- node
notifications:
  slack:
  secure: NczuyRDwZ+o7VdUi/Hu8WY1g92OJtlNBuKuLhC6TlTBIvtK7BdTJEgObxKSF3oRUqpvgRI852VDjpwFPn7FOSm6/LHqNTsQFFWewWmAJ9qMep5DTvOQdHW2ibTc8hgBQ7EPuQu9G/B2/+ybM24LEFzfdmM/ulPu6tDILHQzPfw6rfa4qEOkuTbTrj0NIqapgVLsoPfOMXu+Qs5qNIUboJWMJEmu/5A/QUolOU6rchNTrHd4QXoaeclGWwui+ZyyPO0ODJWVl9l9aBOD7HfGBp0H9ik00glT0P+Zr2uvLV/8lyqBHuQRsCQEs2viCp2UfZCqGcNHrha6ljBwPXQXD5/SIBxwFsPLLlurB+K37ASQTE7YFfyDlDRIRLyKhQcdCT96VinJbWqKANhoHLGDLDAMVYOtVBl9ob1OZfTFi6Mr4yWOf3PMiAXiQxogvFXlNsJk1pig3be3dNg5MHa82g+5ly93y7m0MwM7V7mNW/V2vr8u42w339xraHcjlQrb9TJlcD/10IZWa1Lsm7wsrPDfOG55/Y4iu1/iqh7p+zY+FZ/Jae+ZqNIqN+JkqezQbOXjVd/BTDY1ak/D+jpS94o6pPdG9BGSS32Nu1sCHSAykf6coI2Adn7kEmY2a7NqYYn5EvmQJ4PwmfP3U7isCM3Y/Yk5HTGbbMIDJpO4+QAE=
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
