language: node_js
node_js:
- node
notifications:
  slack:
    secure: Cf8V5GfhUKUn+Bo7Y8UQCTade/eAzUoLEdf/Q34z0vHD1WV0F6lmqxs0K/TlIRaRkXd9jPAryAp2xwZ4GP/Bvf1pAIxnbvoSDeC1oTGG/MUjJxxw4epUlAy+XJfY9DgB6U7QnIhK+Vt2URRSdkeDBwC/OHH6u7c7gS50BOUNfWnFfJ6zfUvnZubtKuAi3UCXdTAWj3Nc1yYh9FSqeI/UY2m3NAnRXxI4lqBsvMQ4FyPQwBxOgNi0BWbZruQC/YKZzDWm98yzAgqFTYiK6yTbq5f0uP0Uk/w2Tq1WY17TGGWuH9igV3xgW/F53sjD17crNmKqUmbl5pPNWcKWZi95t1cjJizvOBq5XnpHiSOSKg6dcnTcIQw84yComIGMNuHCSvEkKrT35Dz/QSQWZ76AHVF4iQRoaYiU/u4+K9pSkcLGeqr7Rh5IPktdtMOT0EUnVq4sICRozn/M3b0iVwk/q5M0IhVMdZjRjQNE+Q/NJwaDB1D7S8NlNjyMk1OD8G/QMsJenXUbsokfaXKZLJorJu6sfiLBsRwTvAmo+MzePGkgkVY1wlxHOiVc4rXeCm2b4k9QW28e/hl4N6BPRLg0UjhdzgMd9UUkGdl2le94VCF8oRgGy8/HEoYgduwAvrlb47KrK2867wVrtsH1TxWmdHaulv/TAjyAji/NkJ+SdAQ=
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
